### ISSUE TITLE
Tool Idea: BNAT-Simulator

### ISSUE THREAD

**Issue by claudijd** [claudijd/bnat#15]
A tool that could be used to quickly create virtualized and portable instances of basic to advanced versions of BNAT.

**Comment by claudijd** [comment]
simply port router code to work in reverse :)

**Comment by bannedit** [comment]
should be easy, you wouldn't even need any internal hosts just something to act like a router, you could simulate all the rest of the traffic.

**Comment by claudijd** [comment]
Implemented and uploaded to repo.

**Comment by bannedit** [comment]
nice =)

**Comment by claudijd** [comment]
Thanks!

I was setting up infrastructure yesterday and it seemed like a waste to buy/build all that hardware for something so simple as basic detection.

A couple modifications to the simulator code and you have every case imaginable beyond what can be configure in hardware and it is something I can bake into specs and integration testing.

Thanks again for the encouragement!

-JC
