### ISSUE TITLE
README.md link broken

### ISSUE THREAD

**Issue by Senjai** [claudijd/bnat#29]
The "What this is about" link is broken in README.md

**Comment by claudijd** [comment]
Richard,

That should be pointing to the project page for BNAT, which contains the readme info about the project.  Unfortunately, whether it be through renaming the project (from BNAT-Suite to BNAT) or through some some other operation I managed to get them out of sync.

Thank you for bringing this to my attention!  I'll take a look at this tomorrow and see if I can get this cleaned up.  I have been thinking about going back to a traditional markdown  readme anyways, so we'll see how it goes.

Cheers,

-Jonathan

**Comment by claudijd** [comment]
I just addressed this.  I'm also doing a bit of an overhaul of the project as a whole to bring it up to snuff so expect more changes as I slog through all the items on my list.  If you have other ideas/feedback, please let me know.

Thanks again!

**Comment by Senjai** [comment]
Wonderful! Will do! :)
